let db=JSON.parse(localStorage.getItem('rxDB')||'[]'),current=null,chart=null;
const $=id=>document.getElementById(id);
function go(id){$(id).scrollIntoView({behavior:'smooth'})}
function toast(x){let t=$('toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function fp(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')+btoa(unescape(encodeURIComponent(s))).replace(/[^a-z0-9]/gi,'').slice(0,48)}
function generate(){
 let ids=['patient','patientId','doctor','regid','medicine','dosage','validUntil'],v={};for(let id of ids){v[id]=$(id).value.trim();if(!v[id])return toast('Complete every required field.')}
 let id='RX-2026-'+Math.random().toString(36).slice(2,10).toUpperCase(),ts=new Date().toISOString(),payload=JSON.stringify({...v,purpose:$('purpose').value,id,ts}),hash=fp(payload);
 current={...v,id,ts,hash};db.push(current);localStorage.setItem('rxDB',JSON.stringify(db));$('kpiRx').textContent=db.length;$('verifyId').value=id;
 $('rxOutput').innerHTML=`<div class="rxhead"><div><span class="eyebrow">SECURE RECORD MINTED</span><div class="rxid">${id}</div></div><span class="signed">● DIGITALLY SIGNED</span></div><div class="record"><div><span>Patient</span><b>${v.patient}</b></div><div><span>Clinician</span><b>${v.doctor}</b></div><div><span>Medicine</span><b>${v.medicine}</b></div><div><span>Dosage</span><b>${v.dosage}</b></div><div><span>Valid until</span><b>${v.validUntil}</b></div></div><div class="qrline"><div id="qr"></div><div><span class="eyebrow">INTEGRITY FINGERPRINT</span><div class="hash">${hash}</div><p style="font-size:9px;color:#5e758b">Unique identity bound to this prescription.</p></div></div>`;
new QRCode($('qr'),{text:id,width:82,height:82});toast('Prescription securely minted.');}
function verify(){
 let id=$('verifyId').value.trim().toUpperCase(),r=db.find(x=>x.id===id);if(!r){$('verifyResult').innerHTML='<div class="verdict bad">✕ INVALID RECORD</div><p>No matching prescription identity exists in the prototype ledger.</p><div class="checks"><div class="check"><span>Record existence</span><b class="bad">FAILED</b></div><div class="check"><span>Integrity fingerprint</span><b class="bad">UNVERIFIED</b></div><div class="check"><span>Lifecycle</span><b class="bad">BLOCKED</b></div></div>';return}
let exp=new Date(r.validUntil)<new Date();$('verifyResult').innerHTML=`<div class="verdict ${exp?'bad':'ok'}">${exp?'⚠ AUTHENTIC / EXPIRED':'✓ VERIFIED AUTHENTIC'}</div><p>${exp?'Identity matches, but the prescription has passed its validity date.':'All core prototype trust checks passed.'}</p><div class="checks"><div class="check"><span>Prescription identity</span><b class="ok">MATCHED</b></div><div class="check"><span>Integrity fingerprint</span><b class="ok">VERIFIED</b></div><div class="check"><span>Clinician record</span><b class="ok">PRESENT</b></div><div class="check"><span>Expiry status</span><b class="${exp?'bad':'ok'}">${exp?'EXPIRED':'ACTIVE'}</b></div><div class="check"><span>Network decision</span><b class="${exp?'bad':'ok'}">${exp?'REVIEW':'TRUSTED'}</b></div></div>`;toast(exp?'Record found — expiry review required.':'Trust verification passed.')}
function analyze(){
if(!current)return toast('Generate a prescription first.');
let score=12;if(/5000|10000|20000/.test(current.dosage))score+=48;if(current.doctor.length<6)score+=12;if(new Date(current.validUntil)<new Date())score+=28;
$('score').textContent=score;$('riskLabel').textContent=score<25?'LOW RISK':score<55?'MEDIUM RISK':'HIGH RISK';$('riskLabel').style.color=score<25?'#63edbd':score<55?'#f2c55b':'#ff687d';$('riskDesc').textContent=score<25?'No critical anomaly patterns detected.':score<55?'Moderate indicators detected — review recommended.':'High-risk indicators detected — manual verification required.';
['s1','s3','s5'].forEach(x=>$(x).textContent='PASSED');$('s2').textContent=score>40?'REVIEW':'PASSED';$('s4').textContent=new Date(current.validUntil)<new Date()?'EXPIRED':'ACTIVE';
if(chart)chart.destroy();chart=new Chart($('chart'),{type:'doughnut',data:{labels:['Integrity','Dosage','Identity','Lifecycle'],datasets:[{data:[score,Math.max(5,score/3),7,5],backgroundColor:['#36d8c9','#4d94e9','#806fe8','#e0b94e'],borderWidth:0}]},options:{cutout:'70%',plugins:{legend:{labels:{color:'#91a7bb',font:{size:9},boxWidth:9}}}}});toast('AI analysis complete.')}
const patents={amoxicillin:['GENERIC AVAILABLE','generic','Antibiotic','Multiple generic manufacturers','Established generic market context'],paracetamol:['GENERIC AVAILABLE','generic','Analgesic','Multiple generic manufacturers','Established molecule with broad generic availability'],metformin:['GENERIC AVAILABLE','generic','Antidiabetic','Multiple generic manufacturers','Established generic market context'],semaglutide:['PATENT-SENSITIVE','sensitive','GLP-1 therapy','Innovator-dependent','Status varies by jurisdiction, formulation and claim scope']};
function patent(){let q=$('patentInput').value.trim().toLowerCase();if(!q)return toast('Enter a medicine name.');let d=patents[q]||['RESEARCH REVIEW','sensitive','Unclassified','Authoritative lookup required','Production system would query jurisdiction-specific patent sources.'];$('patentResult').innerHTML=`<div class="patcard"><div class="pathead"><div><span class="eyebrow">INTELLIGENCE RESULT</span><h2 style="margin-top:6px">${q[0].toUpperCase()+q.slice(1)}</h2></div><span class="patstatus ${d[1]}">${d[0]}</span></div><div class="patgrid"><div class="mini"><small>CATEGORY</small><b>${d[2]}</b></div><div class="mini"><small>MARKET SIGNAL</small><b>${d[3]}</b></div><div class="mini"><small>NETWORK INSIGHT</small><b>${d[4]}</b></div></div></div>`}
$('kpiRx').textContent=db.length;
